### ISSUE TITLE
Module that install modules

### ISSUE THREAD

**Issue by sjrct** [Halibot/halibot-legacy#25]
Probably should be a core module, so one can install other modules from a web address.

It should probably work something like:

```
!module install https://raw.githubusercontent.com/richteer/halibot-modules/master/cat.py
```

or maybe just `!install`. Maybe one word modules look by default in the `halibot-modules` repo by default. As long as this seems sensible, I will get around to it later today or tomorrow.

**Comment by sjrct** [comment]
Probably should also be able to list installed modules regardless of whether they are enabled or not.

Maybe should have the commands:

```
!module install ...
!module remove ...
!module list
```

**Comment by richteer** [comment]
I'm planning on including a `load_module()` method in core for an individual module, so maybe `!module load` or something similar should be implemented as well

**Comment by richteer** [comment]
Added in the PackageManager module in 46dbe2e334d5b9e741f7f1ab2f5cb2417eb17d21
